[tool.poetry]
name = "kinesis"
version = "0.1.0"
description = ""
authors = ["mohitsethi <mohit@sethis.in>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
boto3 = "^1.21.46"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
